name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      ARTEMIS_USERNAME: "guest"
      ARTEMIS_PASSWORD: "guest"
      ARTEMIS_HOST: "localhost"
      ARTEMIS_PORT: 5672
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Run ActiveMQ Artemis
        run: docker-compose up -V -d
        working-directory: ./test/artemis
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release
